//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ValkyrieData.Banking
{

    public partial class TransactionHistory : XPObject
    {
        Transaction fTransaction;
        public Transaction Transaction
        {
            get { return fTransaction; }
            set { SetPropertyValue<Transaction>(nameof(Transaction), ref fTransaction, value); }
        }
        User fUser;
        public User User
        {
            get { return fUser; }
            set { SetPropertyValue<User>(nameof(User), ref fUser, value); }
        }
        DateTime fTimestamp;
        public DateTime Timestamp
        {
            get { return fTimestamp; }
            set { SetPropertyValue<DateTime>(nameof(Timestamp), ref fTimestamp, value); }
        }
        string fMessage;
        public string Message
        {
            get { return fMessage; }
            set { SetPropertyValue<string>(nameof(Message), ref fMessage, value); }
        }
    }

}
