//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ValkyrieData.Banking
{

    public partial class TransactionCategory : XPObject
    {
        string fTitle;
        public string Title
        {
            get { return fTitle; }
            set { SetPropertyValue<string>(nameof(Title), ref fTitle, value); }
        }
        string fIsWithdrawal;
        public string IsWithdrawal
        {
            get { return fIsWithdrawal; }
            set { SetPropertyValue<string>(nameof(IsWithdrawal), ref fIsWithdrawal, value); }
        }
        string fIsDeposit;
        public string IsDeposit
        {
            get { return fIsDeposit; }
            set { SetPropertyValue<string>(nameof(IsDeposit), ref fIsDeposit, value); }
        }
        string fIsLocked;
        public string IsLocked
        {
            get { return fIsLocked; }
            set { SetPropertyValue<string>(nameof(IsLocked), ref fIsLocked, value); }
        }
        [Association(@"TransactionReferencesTransactionCategory")]
        public XPCollection<Transaction> Transactions { get { return GetCollection<Transaction>(nameof(Transactions)); } }
    }

}
